[email]
sender = "prashanthmadival64@gmail.com"
password = "qrmv zvel womj kllw"

[database]
server = "localhost\\SQLEXPRESS"
database = "attendance_db"

[admin]
username = "admin"
password = "admin123"